## name: Alya Sakura (Pastel Sakura Pink)
## author: Antigravity

foreground              #fdf2f8
background              #12080f
selection_foreground    #12080f
selection_background    #f472b6

cursor                  #f472b6
cursor_text_color       #12080f
url_color               #f8fafc

active_border_color     #f472b6
inactive_border_color   #291523
bell_border_color       #f8fafc

wayland_titlebar_color system
macos_titlebar_color system

active_tab_foreground   #12080f
active_tab_background   #f472b6
inactive_tab_foreground #fbcfe8
inactive_tab_background #1c0e18
tab_bar_background      #12080f

# black
color0  #12080f
color8  #291523

# red
color1  #ff0055
color9  #ff0033

# green
color2  #4ade80
color10 #86efac

# yellow
color3  #f8fafc
color11 #fde047

# blue
color4  #f472b6
color12 #38bdf8

# magenta
color5  #f472b6
color13 #f472b6

# cyan
color6  #f8fafc
color14 #5eead4

# white
color7  #fdf2f8
color15 #ffffff
