## name: Blue Archive (Kivotos Sky)
## author: Antigravity

foreground              #f0f9ff
background              #060e1a
selection_foreground    #060e1a
selection_background    #38bdf8

cursor                  #ffd166
cursor_text_color       #060e1a

url_color               #38bdf8

active_border_color     #38bdf8
inactive_border_color   #1d3b61
bell_border_color       #ffd166

wayland_titlebar_color system
macos_titlebar_color system

active_tab_foreground   #060e1a
active_tab_background   #38bdf8
inactive_tab_foreground #93c5fd
inactive_tab_background #0e1c30
tab_bar_background      #040a12

# black
color0  #060e1a
color8  #142944

# red
color1  #f43f5e
color9  #fb7185

# green
color2  #10b981
color10 #34d399

# yellow
color3  #ffd166
color11 #fde047

# blue
color4  #0284c7
color12 #38bdf8

# magenta
color5  #818cf8
color13 #a5b4fc

# cyan
color6  #06b6d4
color14 #67e8f9

# white
color7  #f0f9ff
color15 #ffffff
