## name: Crimson Rose (Camellya / Kurumi)
## author: Antigravity

foreground              #ffe4e6
background              #0d0609
selection_foreground    #0d0609
selection_background    #ff0055

cursor                  #ff758f
cursor_text_color       #0d0609

url_color               #ff0055

active_border_color     #ff0055
inactive_border_color   #361628
bell_border_color       #ffb703

wayland_titlebar_color system
macos_titlebar_color system

active_tab_foreground   #0d0609
active_tab_background   #ff0055
inactive_tab_foreground #fda4af
inactive_tab_background #180b12
tab_bar_background      #080305

# black
color0  #0d0609
color8  #24101b

# red
color1  #ff0055
color9  #ff0033

# green
color2  #4ade80
color10 #86efac

# yellow
color3  #ffb703
color11 #fbbf24

# blue
color4  #e11d48
color12 #f43f5e

# magenta
color5  #ff758f
color13 #fda4af

# cyan
color6  #2dd4bf
color14 #5eead4

# white
color7  #ffe4e6
color15 #ffffff
