## name: Firefly Starlight (Bioluminescent Mint)
## author: Antigravity

foreground              #f0fdfa
background              #071113
selection_foreground    #071113
selection_background    #2dd4bf

cursor                  #2dd4bf
cursor_text_color       #071113
url_color               #fb923c

active_border_color     #2dd4bf
inactive_border_color   #152e34
bell_border_color       #fb923c

wayland_titlebar_color system
macos_titlebar_color system

active_tab_foreground   #071113
active_tab_background   #2dd4bf
inactive_tab_foreground #99f6e4
inactive_tab_background #0d1e22
tab_bar_background      #071113

# black
color0  #071113
color8  #152e34

# red
color1  #ff0055
color9  #ff0033

# green
color2  #4ade80
color10 #86efac

# yellow
color3  #fb923c
color11 #fde047

# blue
color4  #2dd4bf
color12 #38bdf8

# magenta
color5  #2dd4bf
color13 #f472b6

# cyan
color6  #fb923c
color14 #5eead4

# white
color7  #f0fdfa
color15 #ffffff
