## name: Furina Hydro (Fontaine Blue)
## author: Antigravity

foreground              #f0f8ff
background              #050a14
selection_foreground    #050a14
selection_background    #00c2cb

cursor                  #ffd166
cursor_text_color       #050a14

url_color               #00c2cb

active_border_color     #00c2cb
inactive_border_color   #1e365e
bell_border_color       #ffd166

wayland_titlebar_color system
macos_titlebar_color system

active_tab_foreground   #050a14
active_tab_background   #00c2cb
inactive_tab_foreground #a5d8ff
inactive_tab_background #0c172a
tab_bar_background      #03070d

# black
color0  #050a14
color8  #142440

# red
color1  #ff4d6d
color9  #fa5252

# green
color2  #2ec4b6
color10 #38d9a9

# yellow
color3  #ffd166
color11 #ffe066

# blue
color4  #1d8cf8
color12 #4dabf7

# magenta
color5  #9775fa
color13 #b197fc

# cyan
color6  #00c2cb
color14 #22b8cf

# white
color7  #f0f8ff
color15 #ffffff
