## name: Kurumi Tokisaki (Gothic Crimson)
## author: Antigravity

foreground              #fef2f2
background              #090507
selection_foreground    #090507
selection_background    #dc2626

cursor                  #dc2626
cursor_text_color       #090507
url_color               #fbbf24

active_border_color     #dc2626
inactive_border_color   #1f0e17
bell_border_color       #fbbf24

wayland_titlebar_color system
macos_titlebar_color system

active_tab_foreground   #090507
active_tab_background   #dc2626
inactive_tab_foreground #fca5a5
inactive_tab_background #140a0f
tab_bar_background      #090507

# black
color0  #090507
color8  #1f0e17

# red
color1  #ff0055
color9  #ff0033

# green
color2  #4ade80
color10 #86efac

# yellow
color3  #fbbf24
color11 #fde047

# blue
color4  #dc2626
color12 #38bdf8

# magenta
color5  #dc2626
color13 #f472b6

# cyan
color6  #fbbf24
color14 #5eead4

# white
color7  #fef2f2
color15 #ffffff
