## name: Pastel End-4 (Material Lavender)
## author: Antigravity

foreground              #f3eefc
background              #14121a
selection_foreground    #14121a
selection_background    #d0bcff

cursor                  #e8def8
cursor_text_color       #14121a

url_color               #89dceb

active_border_color     #d0bcff
inactive_border_color   #352f44
bell_border_color       #f38ba8

wayland_titlebar_color system
macos_titlebar_color system

active_tab_foreground   #14121a
active_tab_background   #d0bcff
inactive_tab_foreground #cac4d0
inactive_tab_background #1d1926
tab_bar_background      #100e16

mark1_foreground #14121a
mark1_background #d0bcff
mark2_foreground #14121a
mark2_background #e8def8
mark3_foreground #14121a
mark3_background #a6e3a1

# black
color0  #282334
color8  #352f44

# red
color1  #f38ba8
color9  #f38ba8

# green
color2  #a6e3a1
color10 #a6e3a1

# yellow
color3  #f9e2af
color11 #f9e2af

# blue
color4  #89b4fa
color12 #89b4fa

# magenta
color5  #d0bcff
color13 #e8def8

# cyan
color6  #94e2d5
color14 #94e2d5

# white
color7  #cac4d0
color15 #f3eefc
