## name: Silver Wolf (Cyber Violet)
## author: Antigravity

foreground              #f3e8ff
background              #0a0814
selection_foreground    #0a0814
selection_background    #a855f7

cursor                  #00f0ff
cursor_text_color       #0a0814

url_color               #ff007f

active_border_color     #a855f7
inactive_border_color   #261e4c
bell_border_color       #facc15

wayland_titlebar_color system
macos_titlebar_color system

active_tab_foreground   #0a0814
active_tab_background   #a855f7
inactive_tab_foreground #bca7e8
inactive_tab_background #120e24
tab_bar_background      #07050e

# black
color0  #0a0814
color8  #1b1536

# red
color1  #ff007f
color9  #f43f5e

# green
color2  #06d6a0
color10 #34d399

# yellow
color3  #facc15
color11 #fde047

# blue
color4  #6366f1
color12 #818cf8

# magenta
color5  #a855f7
color13 #c084fc

# cyan
color6  #00f0ff
color14 #38bdf8

# white
color7  #f3e8ff
color15 #ffffff
