font_size 12.0
window_padding_width 8
font_family      JetBrainsMono Nerd Font
italic_font      auto
bold_italic_font auto
include theme.conf

background_opacity 0.60
dynamic_background_opacity yes
scrollback_lines 50000
enable_audio_bell no

#cursor_shape beam
cursor_shape block
cursor_blink true
cursor_trail 10
cursor_trail_start_threshold 0 
cursor_trail_decay 0.01 0.08
hide_shadow_decorations yes

tab_bar_edge top
tab_bar_style powerline
tab_powerline_style slanted

#hide_window_decorations yes
#confirm_os_window_close 0
