#!/bin/sh

if [ "$(nmcli radio wifi)" = "enabled" ]; then
  nmcli radio wifi off
  notify-send -e -a "System" -t 1200 "Wi-Fi" "Disabled"
else
  nmcli radio wifi on
  notify-send -e -a "System" -t 1200 "Wi-Fi" "Enabled"
fi
