background {
    monitor =
    path = $HOME/.config/rofi/.current_wallpaper
    blur_passes = 2
    blur_size = 7
    noise = 0.02
    contrast = 0.9
    brightness = 0.7
}

input-field {
    monitor =
    size = 260, 50
    outline_thickness = 2
    dots_size = 0.33
    dots_spacing = 0.15
    dots_center = true
    dots_rounding = -1
    outer_color = rgb(38bdf8)
    inner_color = rgb(0e1c30)
    font_color = rgb(f0f9ff)
    fade_on_empty = false
    fade_timeout = 1000
    placeholder_text = <i><span foreground="##93c5fd">SCHALE://AUTH...</span></i>
    hide_input = false
    rounding = 8
    check_color = rgb(ffd166)
    fail_color = rgb(f43f5e)
    fail_text = <i>VERIFICATION FAILED <b>($ATTEMPTS)</b></i>
    fail_transition = 150
    position = 0, -40
    halign = center
    valign = center
}

label {
    monitor =
    text = cmd[update:1000] echo "$TIME"
    color = rgb(38bdf8)
    font_size = 84
    font_family = JetBrainsMono Nerd Font Bold
    position = 0, 140
    halign = center
    valign = center
    shadow_passes = 3
    shadow_size = 6
    shadow_color = rgba(56, 189, 248, 0.4)
}

label {
    monitor =
    text = cmd[update:1000] date +"%A, %d %B %Y"
    color = rgb(ffd166)
    font_size = 18
    font_family = JetBrainsMono Nerd Font
    position = 0, 80
    halign = center
    valign = center
    shadow_passes = 2
}
