-- hyprland/conf/autostart.lua

hl.on("hyprland.start", function()
    local home = os.getenv("HOME")
    hl.exec_cmd("dbus-update-activation-environment --systemd WAYLAND_DISPLAY XDG_CURRENT_DESKTOP")
    hl.exec_cmd("/usr/lib/polkit-kde-authentication-agent-1")
    hl.exec_cmd("swaync")
    hl.exec_cmd(home .. "/.local/bin/waybar")
    hl.exec_cmd("awww-daemon")
    hl.exec_cmd("sh -c 'if [ -f \"$HOME/.config/rofi/.current_wpe\" ]; then " .. home .. "/.local/bin/wpe-picker --restore; else " .. home .. "/.local/bin/rofi-wallpaper --random; fi'")
    hl.exec_cmd("wl-paste --type text --watch cliphist store")
    hl.exec_cmd("wl-paste --type image --watch cliphist store")
    hl.exec_cmd(home .. "/.local/bin/hypr-workspace-osd")
    hl.exec_cmd("hypridle")
end)
