-- hyprland/conf/autostart.lua

hl.on("hyprland.start", function()
    hl.exec_cmd("/usr/lib/polkit-kde-authentication-agent-1")
    hl.exec_cmd("swaync")
    hl.exec_cmd("waybar")
    hl.exec_cmd("awww-daemon")
    hl.exec_cmd(os.getenv("HOME") .. "/.local/bin/rofi-wallpaper --random")
    hl.exec_cmd("wl-paste --type text --watch cliphist store")
    hl.exec_cmd(os.getenv("HOME") .. "/.local/bin/hypr-workspace-osd")
    hl.exec_cmd("wl-paste --type image --watch cliphist store")
    hl.exec_cmd(os.getenv("HOME") .. "/.local/bin/hypr-workspace-osd")
    hl.exec_cmd("hypridle")
    hl.exec_cmd("dbus-update-activation-environment --systemd WAYLAND_DISPLAY XDG_CURRENT_DESKTOP")
end)
